function bearer(req){const v=String(req.headers.authorization||'');return v.startsWith('Bearer ')?v.slice(7).trim():''}
async function db(path, options={}){const url=process.env.SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error('Supabase server integration is not configured.');const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(`Database request failed: ${r.status}`);return text?JSON.parse(text):null}
async function user(req){const token=bearer(req),url=process.env.SUPABASE_URL,key=process.env.SUPABASE_ANON_KEY||process.env.SUPABASE_PUBLISHABLE_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY;if(!token||!url||!key)return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:key,Authorization:`Bearer ${token}`}});return r.ok?r.json():null}
async function profile(u){const rows=await db(`profiles?id=eq.${encodeURIComponent(u.id)}&select=id,email,display_name,plan,is_admin,vip_until&limit=1`);return rows?.[0]||{id:u.id,email:u.email||null,plan:'Standard',is_admin:false}}
function tierOf(p){const plan=String(p.plan||'Standard').toLowerCase(),vip=Boolean(p.vip_until&&new Date(p.vip_until)>new Date());return p.is_admin||vip?'elite':plan==='elite'?'elite':plan==='pro'?'pro':'standard'}
async function aiResponse(input,system){const gatewayKey=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;if(!gatewayKey)throw new Error('Panic Scanner AI is not configured for this deployment.');const r=await fetch('https://ai-gateway.vercel.sh/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${gatewayKey}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.PANIC_SCANNER_AI_MODEL||'openai/gpt-5.6-luna',store:false,instructions:system,input})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Panic Scanner AI failed.');const text=d.output_text||((d.output||[]).flatMap(x=>x.content||[]).map(x=>x.text||'').filter(Boolean).join('\n'));return text||'I could not produce an answer from the available Panic Scanner context.'}
const {atomicDailyUsage}=require('./_atomic_usage');
module.exports=async function handler(request,response){
 const u=await user(request);if(!u)return response.status(401).json({error:'Sign in required.'});
 try{
  const p=await profile(u),tier=tierOf(p),mode=String(request.query?.mode||'research').toLowerCase();
  if(mode==='ai'||mode==='support'){
   const body=request.body||{},message=String(body.message||'').trim();if(!message)return response.status(400).json({error:'Message required.'});
   if(mode==='ai'&&tier!=='elite')return response.status(403).json({error:'Personal Investment AI is an Elite feature.'});
   const [settings,watchlist,investigations,theses,journal]=await Promise.all([
    db(`user_settings?user_id=eq.${encodeURIComponent(u.id)}&select=sound,haptic,reduce_motion,volume,research_range&limit=1`),
    db(`watchlist_items?user_id=eq.${encodeURIComponent(u.id)}&select=symbol&order=created_at.asc`),
    db(`investigations?user_id=eq.${encodeURIComponent(u.id)}&select=symbol,panic_score,snapshot,created_at&order=created_at.desc&limit=12`),
    db(`theses?user_id=eq.${encodeURIComponent(u.id)}&select=symbol,catalyst,bull_case,bear_case,confirmation,invalidation,created_at&order=created_at.desc&limit=12`),
    db(`journal_entries?user_id=eq.${encodeURIComponent(u.id)}&select=entry_type,symbol,title,body,metadata,created_at&order=created_at.desc&limit=12`)
   ]);
   const context=JSON.stringify({account:{email:p.email,displayName:p.display_name||null,plan:tier},settings:settings?.[0]||{},watchlist:(watchlist||[]).map(x=>x.symbol),recentInvestigations:investigations||[],recentTheses:theses||[],recentJournal:journal||[]});
   const system=mode==='support'?`You are Panic Scanner Support, the product's dedicated in-app support agent. You are not a generic chatbot. Help the authenticated user use Panic Scanner, understand its research workflow, plans, settings, billing concepts and investment-research features. Use the workspace context below when relevant. Never claim you performed an action you cannot perform. For billing/account changes, explain the next safe step. Keep answers concise, friendly and practical. If the user asks for personalized investment decisions, explain that Support is for product help and point them to the Personal Investment AI if their plan includes it. WORKSPACE CONTEXT: ${context}`:`You are the Personal Investment AI inside Panic Scanner. Your job is to help the user investigate opportunities, challenge theses and build disciplined investment plans using only the context and research supplied by Panic Scanner plus the user's message. Do not promise profits or certainty. Do not invent market data, prices, news or holdings. Clearly label assumptions and missing data. When discussing a possible plan, focus on position sizing, maximum loss, invalidation, risk/reward, concentration and what evidence would change the thesis. Challenge weak reasoning instead of agreeing automatically. If the user asks what to buy, frame it as research and a decision framework rather than a guarantee. Remember the user's saved Panic Scanner work and make the conversation feel continuous and personal. WORKSPACE CONTEXT: ${context}`;
   const answer=await aiResponse(message,system);return response.status(200).json({ok:true,mode,answer,plan:tier,generatedAt:new Date().toISOString()});
  }
  const symbol=String(request.query?.symbol||'').trim().toUpperCase(),depth=String(request.query?.depth||'pro').toLowerCase();if(!symbol)return response.status(400).json({error:'Missing stock symbol.'});
  const requested=depth==='elite'?'elite':depth==='pro'?'pro':'standard';if(requested==='elite'&&tier!=='elite')return response.status(403).json({error:'Elite research is available on Elite only.'});if(requested==='pro'&&tier==='standard')return response.status(403).json({error:'Pro research requires Pro or Elite.'});
  const key=process.env.ALPHA_VANTAGE_API_KEY;if(!key)return response.status(500).json({error:'Market-data service is not configured.'});
  async function av(fn,extra={}){const params=new URLSearchParams({function:fn,apikey:key,...extra});if(fn!=='NEWS_SENTIMENT')params.set('symbol',symbol);const r=await fetch(`https://www.alphavantage.co/query?${params}`),d=await r.json();if(d.Note)throw Error('Market-data API limit reached. Try again later.');if(d['Error Message'])throw Error('No data returned for this symbol.');return d}
  const [overview,news]=await Promise.all([av('OVERVIEW'),av('NEWS_SENTIMENT',{tickers:symbol,limit:requested==='elite'?'12':'6',sort:'LATEST'})]);let income=null;if(requested==='elite'){try{income=await av('INCOME_STATEMENT')}catch(_){}}
  if(tier==='standard'){const day=new Date().toISOString().slice(0,10),allowed=await atomicDailyUsage(db,u.id,day,1);if(!allowed)return response.status(429).json({error:'Your 1 free deep search for today has been used. Upgrade to Pro for expanded research.'});}
  const articles=(news.feed||[]).slice(0,requested==='elite'?12:6).map(a=>({title:a.title,source:a.source,url:a.url,time:a.time_published,sentiment:a.overall_sentiment_label,score:Number(a.overall_sentiment_score||0),summary:a.summary}));const revenue=(income?.annualReports||[]).slice(0,5).map(x=>Number(x.totalRevenue)).filter(Number.isFinite),eps=(income?.annualReports||[]).slice(0,5).map(x=>Number(x.eps)).filter(Number.isFinite);const avg=articles.length?articles.reduce((s,a)=>s+a.score,0)/articles.length:0,pos=articles.filter(a=>/positive|bullish/i.test(a.sentiment)).length,neg=articles.filter(a=>/negative|bearish/i.test(a.sentiment)).length;const revenueGrowth=revenue.length>=2&&revenue[1]?((revenue[0]-revenue[1])/Math.abs(revenue[1]))*100:null,epsGrowth=eps.length>=2&&eps[1]?((eps[0]-eps[1])/Math.abs(eps[1]))*100:null;let quality=50;if(revenueGrowth!==null)quality+=revenueGrowth>0?12:-12;if(epsGrowth!==null)quality+=epsGrowth>0?15:-15;if(avg>.15)quality+=8;if(avg<-.15)quality-=8;quality=Math.max(0,Math.min(100,Math.round(quality)));const verdict=quality>=70?'Fundamentals look resilient':quality<=35?'Fundamentals show meaningful weakness':'Fundamentals are mixed';
  return response.status(200).json({symbol,depth:requested,plan:tier,generatedAt:new Date().toISOString(),company:overview.Name||symbol,fundamentals:{sector:overview.Sector||'—',industry:overview.Industry||'—',description:overview.Description||'',marketCap:overview.MarketCapitalization||null,pe:overview.PERatio||null,peg:overview.PEGRatio||null,eps:overview.EPS||null,revenueTTM:overview.RevenueTTM||null,profitMargin:overview.ProfitMargin||null,operatingMargin:overview.OperatingMarginTTM||null,beta:overview.Beta||null,dividendYield:overview.DividendYield||null,revenueGrowth,epsGrowth},news:{articles,averageSentiment:avg,positive:pos,negative:neg},earnings:requested==='elite'?{annualReports:income?.annualReports||[],eps,revenue}:null,investigation:{quality,verdict,steps:[{id:'market',label:'Market reaction',status:'complete'},{id:'technical',label:'Technical condition',status:'complete'},{id:'fundamentals',label:'Fundamentals',status:'complete',detail:verdict},{id:'catalysts',label:'Catalysts & news',status:articles.length?'complete':'limited'},{id:'risk',label:'Risk assessment',status:'complete'},{id:'conclusion',label:'Final conclusion',status:'complete'}]}});
 }catch(e){console.error('investigate error',e);return response.status(502).json({error:e.message||'Investigation failed.'})}
};