const fs = require('fs');
const path = require('path');

export default function handler(req, res) {
  let html = fs.readFileSync(path.join(process.cwd(), 'index.html'), 'utf8');
  const css = `<style id="panic-scanner-ux3-fix">
.psfix-modal{position:fixed;inset:0;z-index:1000;background:#000d;backdrop-filter:blur(18px);padding:12px;overflow:auto;display:none}.psfix-modal.open{display:block}.psfix-shell{width:min(1120px,100%);min-height:calc(100dvh - 24px);margin:auto;background:#0b1119;border:1px solid #273247;border-radius:24px;box-shadow:0 35px 120px #000e;overflow:hidden}.psfix-head{display:flex;justify-content:space-between;align-items:center;padding:20px 24px;border-bottom:1px solid var(--line);background:#0b1119f7;position:sticky;top:0;z-index:2}.psfix-head b{font-size:18px}.psfix-head span{display:block;color:var(--muted);font-size:9px;margin-top:5px}.psfix-close{width:38px;height:38px;border:1px solid var(--line);border-radius:11px;background:#121a25;color:#fff;font-size:22px}.psfix-body{padding:24px}.psfix-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.psfix-plan{padding:21px;border:1px solid var(--line);border-radius:19px;background:linear-gradient(180deg,#111925,#0d141d);position:relative}.psfix-plan.pro{border-color:#786cff88}.psfix-plan.elite{border-color:#f5c85c77}.psfix-plan h3{margin:0;font-size:21px}.psfix-price{font-size:30px;font-weight:1000;margin:8px 0}.psfix-plan p,.psfix-plan li{color:#cbd2df;font-size:10px;line-height:1.55}.psfix-plan ul{padding-left:18px;min-height:145px}.psfix-plan button{width:100%;border:0;border-radius:11px;padding:12px;font-weight:1000;background:#fff}.psfix-plan.pro button{background:var(--purple);color:#fff}.psfix-plan.elite button{background:var(--yellow);color:#111}.psfix-settings{display:grid;grid-template-columns:1fr 1fr;gap:14px}.psfix-group{border:1px solid var(--line);border-radius:17px;background:#0e151f;overflow:hidden}.psfix-group h3{margin:0;padding:15px 16px;border-bottom:1px solid var(--line);font-size:10px;letter-spacing:1.4px;text-transform:uppercase;color:#7d899d}.psfix-setting{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 16px;border-top:1px solid var(--line)}.psfix-setting b{font-size:10px}.psfix-setting p{margin:3px 0 0;color:var(--muted);font-size:8px}.psfix-toggle{width:45px;height:26px;border-radius:99px;border:1px solid #344054;background:#171f2d;position:relative}.psfix-toggle i{position:absolute;left:2px;top:2px;width:20px;height:20px;border-radius:50%;background:#77849a}.psfix-toggle.on{background:#2b2256;border-color:#786cff77}.psfix-toggle.on i{left:21px;background:var(--purple)}.psfix-select{background:#080d15;color:#fff;border:1px solid var(--line);border-radius:9px;padding:8px;font-size:9px}.psfix-range{width:110px;accent-color:var(--purple)}
@media(max-width:620px){.psfix-modal{padding:0}.psfix-shell{min-height:100dvh;border:0;border-radius:0}.psfix-head{padding:16px 15px}.psfix-body{padding:15px 13px 30px}.psfix-plans,.psfix-settings{grid-template-columns:1fr}.psfix-plan ul{min-height:auto}}
</style>`;
  const plans = `<div class="psfix-modal" id="psfixPlans"><div class="psfix-shell"><div class="psfix-head"><div><b>Plans &amp; Subscriptions</b><span>Everything available across Standard, Pro and Elite.</span></div><button class="psfix-close" data-close="psfixPlans">×</button></div><div class="psfix-body"><div class="psfix-plans"><div class="psfix-plan"><h3>Standard</h3><div class="psfix-price">Free</div><p>Core scanner for understanding market reactions.</p><ul><li>Stock and company search</li><li>Price-reaction analysis</li><li>Interactive charts</li><li>Core market metrics</li><li>Reaction overview</li></ul><button>Current plan</button></div><div class="psfix-plan pro"><h3>Pro</h3><div class="psfix-price">Premium</div><p>Deep research into why a move happened.</p><ul><li>Everything in Standard</li><li>Deep Investigation</li><li>Technical + fundamental evidence</li><li>Company-specific live news</li><li>Catalyst and risk context</li></ul><button onclick="toast('Pro checkout is not connected yet.')">Choose Pro</button></div><div class="psfix-plan elite"><h3>Elite</h3><div class="psfix-price">Premium+</div><p>Full stress-to-recovery research mapping.</p><ul><li>Everything in Pro</li><li>Elite Market Reaction Map</li><li>Stress and recovery-watch zones</li><li>Exact date and price inspection</li><li>Maximum research access</li></ul><button onclick="toast('Elite checkout is not connected yet.')">Choose Elite</button></div></div></div></div></div>`;
  const settings = `<div class="psfix-modal" id="psfixSettings"><div class="psfix-shell"><div class="psfix-head"><div><b>Settings</b><span>Control your Panic Scanner experience.</span></div><button class="psfix-close" data-close="psfixSettings">×</button></div><div class="psfix-body"><div class="psfix-settings"><div class="psfix-group"><h3>Workspace</h3><div class="psfix-setting"><div><b>Compact layout</b><p>Fit more research on screen.</p></div><button class="psfix-toggle" data-toggle><i></i></button></div><div class="psfix-setting"><div><b>Reduce motion</b><p>Use simpler transitions.</p></div><button class="psfix-toggle" data-toggle><i></i></button></div><div class="psfix-setting"><div><b>Remember last research</b><p>Open your previous security when you return.</p></div><button class="psfix-toggle on" data-toggle><i></i></button></div></div><div class="psfix-group"><h3>Charts &amp; data</h3><div class="psfix-setting"><div><b>Default chart range</b><p>First range shown for analysis.</p></div><select class="psfix-select"><option>60 days</option><option>40 days</option><option>20 days</option><option>All available</option></select></div><div class="psfix-setting"><div><b>Price precision</b><p>Control displayed price detail.</p></div><select class="psfix-select"><option>Automatic</option><option>2 decimals</option><option>0 decimals</option></select></div></div><div class="psfix-group"><h3>Notifications</h3><div class="psfix-setting"><div><b>Market alerts</b><p>Alerts for major reactions.</p></div><button class="psfix-toggle on" data-toggle><i></i></button></div><div class="psfix-setting"><div><b>Live news alerts</b><p>Important company headlines.</p></div><button class="psfix-toggle on" data-toggle><i></i></button></div></div><div class="psfix-group"><h3>Sound &amp; haptics</h3><div class="psfix-setting"><div><b>Sound effects</b><p>Interface confirmation sounds.</p></div><button class="psfix-toggle on" data-toggle><i></i></button></div><div class="psfix-setting"><div><b>Volume</b><p>Interface sound level.</p></div><input class="psfix-range" type="range" min="0" max="100" value="70"></div><div class="psfix-setting"><div><b>Haptic feedback</b><p>Light feedback on supported mobile devices.</p></div><button class="psfix-toggle on" data-toggle><i></i></button></div></div></div></div></div>`;
  const script = `<script>(function(){
    const $=id=>document.getElementById(id);
    const open=id=>{const m=$(id);if(!m)return;document.querySelectorAll('.psfix-modal.open').forEach(x=>x.classList.remove('open'));m.classList.add('open');document.body.style.overflow='hidden'};
    const close=id=>{const m=$(id);if(!m)return;m.classList.remove('open');if(!document.querySelector('.psfix-modal.open'))document.body.style.overflow=''};
    window.psFixOpen=open;window.psFixClose=close;
    function bind(){
      document.querySelectorAll('.side > .nav').forEach(n=>{const label=(n.querySelector('span')?.textContent||'').trim().toLowerCase();if(label==='plans')n.onclick=e=>{e.preventDefault();open('psfixPlans')};if(label==='settings')n.onclick=e=>{e.preventDefault();open('psfixSettings')};if(label==='watchlist')n.onclick=e=>{e.preventDefault();if(typeof go==='function')go('watchlist')}});
      document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));
      document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>b.classList.toggle('on'));
      document.querySelectorAll('.psfix-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)close(m.id)}));
      document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.psfix-modal.open').forEach(m=>close(m.id))});
    }
    if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
  })();</script>`;
  html=html.replace('</body>',css+plans+settings+script+'</body>');
  res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, max-age=0, must-revalidate');res.status(200).send(html);
}
