const fs = require('fs');
const path = require('path');

export default function handler(req, res) {
  let html = fs.readFileSync(path.join(process.cwd(), 'index.html'), 'utf8');

  const style = `<style id="panic-scanner-ux2">
  /* Production UX pass */
  #accountModal,#plansModal,#settingsModal,.accountBtn{display:none!important}
  .ps2-teaser{margin-top:34px}.ps2-teaser-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.ps2-teaser-card{padding:19px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(180deg,#101722,#0b1018);position:relative;overflow:hidden}.ps2-teaser-card.pro{border-color:#786cff66}.ps2-teaser-card.elite{border-color:#f5c85c66}.ps2-kicker{font-size:8px;letter-spacing:1.5px;color:var(--purple);font-weight:1000}.ps2-teaser-card.elite .ps2-kicker{color:#f5c85c}.ps2-teaser-card h3{margin:8px 0 6px;font-size:16px}.ps2-teaser-card p{margin:0;color:var(--muted);font-size:10px;line-height:1.55}.ps2-badge{position:absolute;right:12px;top:12px;font-size:7px;letter-spacing:1px;padding:5px 7px;border-radius:99px;color:#b9afff;border:1px solid #786cff55}.ps2-teaser-card.elite .ps2-badge{color:#f5c85c;border-color:#f5c85c55}
  .ps2-modal{position:fixed;inset:0;z-index:900;background:#000d;backdrop-filter:blur(18px);padding:max(10px,env(safe-area-inset-top)) 12px max(12px,env(safe-area-inset-bottom));overflow:auto;display:none}.ps2-modal.open{display:block}.ps2-shell{width:min(1120px,100%);min-height:min(760px,calc(100dvh - 20px));margin:0 auto;background:#0b1119;border:1px solid #273247;border-radius:24px;box-shadow:0 35px 120px #000e;overflow:hidden;display:flex;flex-direction:column}.ps2-head{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:21px 24px;border-bottom:1px solid var(--line);background:#0b1119f7;position:sticky;top:0;z-index:3}.ps2-head b{font-size:18px}.ps2-head span{display:block;color:var(--muted);font-size:9px;margin-top:5px}.ps2-close{width:38px;height:38px;border:1px solid var(--line);border-radius:11px;background:#121a25;color:#fff;font-size:22px;flex:none}.ps2-body{padding:24px;overflow:auto}.ps2-plans{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.ps2-plan{padding:21px;border:1px solid var(--line);border-radius:19px;background:linear-gradient(180deg,#111925,#0d141d);position:relative}.ps2-plan.pro{border-color:#786cff88;box-shadow:0 0 0 1px #786cff18}.ps2-plan.elite{border-color:#f5c85c77}.ps2-plan h3{margin:0;font-size:21px}.ps2-price{font-size:30px;font-weight:1000;margin:8px 0 5px}.ps2-plan-desc{color:var(--muted);font-size:10px;line-height:1.5;min-height:32px}.ps2-plan ul{padding-left:18px;color:#cbd2df;font-size:9px;line-height:1.9;margin:14px 0 18px;min-height:150px}.ps2-plan li::marker{color:#71809a}.ps2-plan.pro li::marker{color:var(--purple)}.ps2-plan.elite li::marker{color:#f5c85c}.ps2-cta{width:100%;border:0;border-radius:11px;padding:12px;font-weight:1000;background:#fff;color:#07090f}.ps2-plan.pro .ps2-cta{background:var(--purple);color:#fff}.ps2-plan.elite .ps2-cta{background:var(--yellow);color:#111}.ps2-tag{position:absolute;right:14px;top:14px;border-radius:99px;padding:5px 8px;font-size:7px;letter-spacing:1px;color:#9aa7bc;border:1px solid var(--line)}.ps2-plan.pro .ps2-tag{color:#b9afff;border-color:#786cff66}.ps2-plan.elite .ps2-tag{color:#f5c85c;border-color:#f5c85c55}.ps2-compare{margin-top:20px;border:1px solid var(--line);border-radius:16px;overflow:hidden}.ps2-row{display:grid;grid-template-columns:1.6fr repeat(3,1fr);border-top:1px solid var(--line)}.ps2-row:first-child{border-top:0;background:#111925}.ps2-row span{padding:12px;font-size:9px}.ps2-row span:not(:first-child){text-align:center;border-left:1px solid var(--line)}.ps2-yes{color:var(--green);font-weight:1000}.ps2-no{color:#596579}.ps2-note{margin-top:15px;padding:13px 15px;border:1px solid #786cff33;background:#111525;border-radius:13px;color:var(--muted);font-size:9px;line-height:1.5}
  .ps2-settings{display:grid;grid-template-columns:1fr 1fr;gap:14px}.ps2-group{border:1px solid var(--line);border-radius:17px;background:#0e151f;overflow:hidden}.ps2-group h3{margin:0;padding:15px 16px;border-bottom:1px solid var(--line);font-size:10px;letter-spacing:1.4px;text-transform:uppercase;color:#7d899d}.ps2-setting{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 16px;border-top:1px solid var(--line)}.ps2-setting:first-of-type{border-top:0}.ps2-setting b{font-size:10px}.ps2-setting p{margin:3px 0 0;color:var(--muted);font-size:8px;line-height:1.45}.ps2-toggle{width:45px;height:26px;border-radius:99px;border:1px solid #344054;background:#171f2d;position:relative;flex:none}.ps2-toggle i{position:absolute;left:2px;top:2px;width:20px;height:20px;border-radius:50%;background:#77849a;transition:.16s}.ps2-toggle.on{background:#2b2256;border-color:#786cff77}.ps2-toggle.on i{left:21px;background:var(--purple)}.ps2-select{background:#080d15;color:#fff;border:1px solid var(--line);border-radius:9px;padding:8px 9px;font-size:9px}.ps2-range{width:120px;accent-color:var(--purple)}
  .ps2-news-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.ps2-news-meta{display:flex;align-items:center;gap:8px}.ps2-live{display:inline-flex;align-items:center;gap:6px;color:var(--green);font-size:9px;font-weight:1000}.ps2-live i{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px #35d59d15}.ps2-refresh{border:1px solid var(--line);background:#111925;color:#fff;border-radius:9px;padding:7px 10px;font-size:8px;font-weight:900}.ps2-news-item{padding:13px 0;border-top:1px solid var(--line)}.ps2-news-item b{font-size:11px;line-height:1.35}.ps2-news-item a{color:inherit;text-decoration:none}.ps2-news-item a:hover{text-decoration:underline}.ps2-news-item small{display:block;color:var(--muted);font-size:8px;margin-top:5px;line-height:1.45}.ps2-sent{font-size:9px;font-weight:1000;margin-top:6px}.ps2-news-error{padding:13px;border:1px solid #ff526633;background:#1a1015;border-radius:11px;color:#ff8794;font-size:9px;line-height:1.5}
  @media(max-width:900px){.ps2-teaser-grid,.ps2-plans{grid-template-columns:1fr}.ps2-settings{grid-template-columns:1fr}.ps2-plan ul{min-height:auto}.ps2-shell{min-height:calc(100dvh - 20px)}.ps2-compare{overflow:auto}.ps2-row{min-width:650px}}
  @media(max-width:620px){.ps2-teaser{margin-top:24px}.ps2-teaser-grid{grid-template-columns:1fr}.ps2-modal{padding:0}.ps2-shell{border-radius:0;border:0;min-height:100dvh}.ps2-head{padding:16px 15px}.ps2-body{padding:15px 13px 30px}.ps2-plan{padding:18px}.ps2-compare{display:none}.ps2-setting{align-items:flex-start}.ps2-range{width:105px}.ps2-close{width:36px;height:36px}.ps2-news-item b{font-size:10px}}
  </style>`;

  const teaser = `<section class="ps2-teaser"><div class="sectionHead"><div><h2>See what deeper research unlocks</h2><p>Standard lets you understand the move. The higher plans add the evidence and visual depth for when the move matters.</p></div></div><div class="ps2-teaser-grid"><article class="ps2-teaser-card pro"><span class="ps2-badge">PRO</span><div class="ps2-kicker">DEEP INVESTIGATION</div><h3>Connect the dots</h3><p>Technical condition, fundamentals, catalysts, risk and live news brought into one structured research workflow.</p></article><article class="ps2-teaser-card pro"><span class="ps2-badge">PRO</span><div class="ps2-kicker">NEWS + EVIDENCE</div><h3>Know what moved it</h3><p>See the latest company-specific headlines beside the price reaction instead of hunting for the story yourself.</p></article><article class="ps2-teaser-card elite"><span class="ps2-badge">ELITE</span><div class="ps2-kicker">REACTION MAP</div><h3>Watch stress become recovery</h3><p>Map market-stress and recovery-watch zones directly over the price path with exact dates and prices.</p></article></div></section>`;

  const overlays = `<button id="ps2AccountButton" class="accountBtn" style="display:block" onclick="ps2Open('ps2Account')">Account &amp; Plans</button>
  <div class="ps2-modal" id="ps2Account"><div class="ps2-shell"><div class="ps2-head"><div><b>Account &amp; Plans</b><span>Everything in one place — account, access and research depth.</span></div><button class="ps2-close" onclick="ps2Close('ps2Account')">×</button></div><div class="ps2-body"><div class="ps2-plans"><div class="ps2-plan"><span class="ps2-tag">FREE</span><h3>Standard</h3><div class="ps2-price">Free</div><div class="ps2-plan-desc">The essential scanner for understanding a market reaction.</div><ul><li>Search stocks and companies</li><li>Core price-reaction analysis</li><li>Interactive price charts</li><li>Basic market metrics</li><li>Reaction overview</li></ul><button class="ps2-cta" onclick="toast('Standard is active.')">Current plan</button></div><div class="ps2-plan pro"><span class="ps2-tag">MOST POPULAR</span><h3>Pro</h3><div class="ps2-price">Premium</div><div class="ps2-plan-desc">For users who want to investigate the reason behind the move.</div><ul><li>Everything in Standard</li><li>Deep Investigation workflow</li><li>Technical + fundamental evidence</li><li>Company-specific live news</li><li>Catalyst and risk context</li></ul><button class="ps2-cta" onclick="toast('Pro checkout is not connected yet.')">Choose Pro</button></div><div class="ps2-plan elite"><span class="ps2-tag">ADVANCED</span><h3>Elite</h3><div class="ps2-price">Premium+</div><div class="ps2-plan-desc">The complete research layer for serious market investigation.</div><ul><li>Everything in Pro</li><li>Elite Market Reaction Map</li><li>Stress and recovery-watch zones</li><li>Exact visual date/price inspection</li><li>Maximum research access</li></ul><button class="ps2-cta" onclick="toast('Elite checkout is not connected yet.')">Choose Elite</button></div></div><div class="ps2-compare"><div class="ps2-row"><span><b>Feature</b></span><span><b>Standard</b></span><span><b>Pro</b></span><span><b>Elite</b></span></div><div class="ps2-row"><span>Search + core reaction</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span></div><div class="ps2-row"><span>Interactive charts</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span></div><div class="ps2-row"><span>Deep investigation</span><span class="ps2-no">—</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span></div><div class="ps2-row"><span>Company-specific live news</span><span class="ps2-no">—</span><span class="ps2-yes">✓</span><span class="ps2-yes">✓</span></div><div class="ps2-row"><span>Elite reaction map</span><span class="ps2-no">—</span><span class="ps2-no">—</span><span class="ps2-yes">✓</span></div></div><div class="ps2-note">Pricing and checkout are intentionally not faked here. The product UI is ready; payment processing will be connected when the billing system is added.</div></div></div></div>
  <div class="ps2-modal" id="ps2Plans"><div class="ps2-shell"><div class="ps2-head"><div><b>Plans</b><span>Choose the research depth that fits the way you use Panic Scanner.</span></div><button class="ps2-close" onclick="ps2Close('ps2Plans')">×</button></div><div class="ps2-body"><div class="ps2-plans"><div class="ps2-plan"><h3>Standard</h3><div class="ps2-price">Free</div><div class="ps2-plan-desc">Understand what happened.</div><ul><li>Stock/company search</li><li>Price reaction</li><li>Interactive chart</li><li>Core metrics</li></ul></div><div class="ps2-plan pro"><span class="ps2-tag">MOST POPULAR</span><h3>Pro</h3><div class="ps2-price">Premium</div><div class="ps2-plan-desc">Understand why it may have happened.</div><ul><li>Deep Investigation</li><li>Technical + fundamental evidence</li><li>Live company news</li><li>Catalyst context</li></ul></div><div class="ps2-plan elite"><span class="ps2-tag">ADVANCED</span><h3>Elite</h3><div class="ps2-price">Premium+</div><div class="ps2-plan-desc">Map the full stress-to-recovery picture.</div><ul><li>Everything in Pro</li><li>Elite Market Reaction Map</li><li>Stress zones</li><li>Recovery-watch zones</li></ul></div></div></div></div></div>
  <div class="ps2-modal" id="ps2Settings"><div class="ps2-shell"><div class="ps2-head"><div><b>Settings</b><span>Professional controls for your research workspace.</span></div><button class="ps2-close" onclick="ps2Close('ps2Settings')">×</button></div><div class="ps2-body"><div class="ps2-settings"><div class="ps2-group"><h3>Workspace</h3><div class="ps2-setting"><div><b>Compact layout</b><p>Fit more research on screen.</p></div><button class="ps2-toggle" onclick="this.classList.toggle('on')"><i></i></button></div><div class="ps2-setting"><div><b>Reduce motion</b><p>Use simpler transitions.</p></div><button class="ps2-toggle" onclick="this.classList.toggle('on')"><i></i></button></div><div class="ps2-setting"><div><b>Remember last research</b><p>Open your previous security when you return.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div></div><div class="ps2-group"><h3>Charts &amp; data</h3><div class="ps2-setting"><div><b>Default chart range</b><p>First range shown on a stock analysis.</p></div><select class="ps2-select"><option>60 days</option><option>40 days</option><option>20 days</option><option>All available</option></select></div><div class="ps2-setting"><div><b>Price precision</b><p>Choose how exact displayed prices are.</p></div><select class="ps2-select"><option>Automatic</option><option>2 decimals</option><option>0 decimals</option></select></div><div class="ps2-setting"><div><b>Chart point details</b><p>Show date, price, volume and drawdown while dragging.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div></div><div class="ps2-group"><h3>Notifications</h3><div class="ps2-setting"><div><b>Market alerts</b><p>Alerts for saved research and major reactions.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div><div class="ps2-setting"><div><b>Live news alerts</b><p>Surface important company-specific headlines.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div><div class="ps2-setting"><div><b>Alert frequency</b><p>Control how often alerts can appear.</p></div><select class="ps2-select"><option>Important only</option><option>Balanced</option><option>All available</option></select></div></div><div class="ps2-group"><h3>Sound &amp; haptics</h3><div class="ps2-setting"><div><b>Sound effects</b><p>Interface confirmation sounds.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div><div class="ps2-setting"><div><b>Volume</b><p>Interface sound level.</p></div><input class="ps2-range" type="range" min="0" max="100" value="70"></div><div class="ps2-setting"><div><b>Haptic feedback</b><p>Light feedback on supported mobile devices.</p></div><button class="ps2-toggle on" onclick="this.classList.toggle('on')"><i></i></button></div></div></div></div></div></div>`;

  const js = `<script id="panic-scanner-ux2-js">(function(){
    const $=id=>document.getElementById(id);
    function ps2Open(id){const m=$(id);if(!m)return;m.classList.add('open');document.body.style.overflow='hidden'}
    function ps2Close(id){const m=$(id);if(!m)return;m.classList.remove('open');if(!document.querySelector('.ps2-modal.open'))document.body.style.overflow=''}
    window.ps2Open=ps2Open;window.ps2Close=ps2Close;
    window.openModal=function(id){if(id==='plansModal')return ps2Open('ps2Plans');if(id==='settingsModal')return ps2Open('ps2Settings');if(id==='accountModal')return ps2Open('ps2Account');return null};
    window.closeModal=function(id){if(id==='plansModal')return ps2Close('ps2Plans');if(id==='settingsModal')return ps2Close('ps2Settings');if(id==='accountModal')return ps2Close('ps2Account');return null};
    function esc(x){return String(x??'').replace(/[&<>\\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\\"':'&quot;',\"'\":'&#39;'}[c]))}
    function renderLiveNews(items,updated){const box=$('news');if(!box)return;const head='<div class="ps2-news-head"><div class="ps2-news-meta"><span class="ps2-live"><i></i>LIVE NEWS</span><small style="color:var(--muted);font-size:8px">'+esc(updated||'Just now')+'</small></div><button class="ps2-refresh" id="ps2NewsRefresh">Refresh</button></div>';if(!items?.length){box.innerHTML=head+'<div class="loading">No company-specific headlines are available right now.</div>';bindRefresh();return}box.innerHTML=head+items.slice(0,8).map(n=>{const s=String(n.sentiment||'Neutral'),cls=/negative|bearish/i.test(s)?'red':/positive|bullish/i.test(s)?'green':'';const title=esc(n.title||'Market headline'),url=esc(n.url||'');return '<div class="ps2-news-item"><b>'+((url&&/^https:\\/\\//.test(url))?'<a href="'+url+'" target="_blank" rel="noopener">'+title+'</a>':title)+'</b><small>'+esc(n.source||'Market news')+' · '+esc(n.time||'Recent')+'</small><div class="ps2-sent '+cls+'">'+esc(s)+'</div></div>'}).join('');bindRefresh()}
    function bindRefresh(){const b=$('ps2NewsRefresh');if(b)b.onclick=function(){if(window.__ps2Symbol)loadLiveNews(window.__ps2Symbol,true)}}
    async function loadLiveNews(symbol,manual){if(!symbol||!$('news'))return;window.__ps2Symbol=symbol;$('news').innerHTML='<div class="loading"><span class="ps2-live"><i></i> LIVE NEWS</span> Loading company-specific headlines…</div>';try{const r=await fetch('/api/news?symbol='+encodeURIComponent(symbol)+'&_='+Date.now(),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Live news unavailable');renderLiveNews(d.articles,d.updatedAt?new Date(d.updatedAt).toLocaleString():'Just now')}catch(e){$('news').innerHTML='<div class="ps2-news-error"><b>Live news unavailable</b><br>'+esc(e.message)+'<br><br><button class="ps2-refresh" onclick="loadLiveNews(\''+esc(symbol)+'\',true)">Try again</button></div>'}}
    window.loadLiveNews=loadLiveNews;
    const originalAnalyze=window.analyze;if(typeof originalAnalyze==='function'){window.analyze=async function(symbol,name){const r=await originalAnalyze(symbol,name);loadLiveNews(symbol);return r}}
    const originalInvestigate=window.investigate;if(typeof originalInvestigate==='function'){window.investigate=function(){const symbol=window.current?.symbol||window.current?.ticker||window.__ps2Symbol;if(symbol)loadLiveNews(symbol,true);return originalInvestigate()}}
    document.addEventListener('DOMContentLoaded',function(){
      const navs=document.querySelectorAll('.nav');navs.forEach(n=>{const label=(n.querySelector('span')?.textContent||'').trim().toLowerCase();if(label==='plans')n.onclick=e=>{e.preventDefault();ps2Open('ps2Plans')};if(label==='settings')n.onclick=e=>{e.preventDefault();ps2Open('ps2Settings')};if(label==='account')n.onclick=e=>{e.preventDefault();ps2Open('ps2Account')}});
      document.querySelectorAll('.ps2-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)ps2Close(m.id)}));
      document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.ps2-modal.open').forEach(m=>ps2Close(m.id))});
      const q=$('q');if(q&&q.placeholder)q.placeholder='Search a stock or company';
    });
  })();</script>`;

  html = html.replace('</style>', style + '</style>');
  html = html.replace('</main>', teaser + '</main>');
  html = html.replace('</body>', overlays + js + '</body>');

  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('Cache-Control','no-store, max-age=0, must-revalidate');
  return res.status(200).send(html);
}
