import ux2 from './ux2.js';

export default async function handler(req, res) {
  const send = res.send.bind(res);
  const intercepted = {
    ...res,
    status(code) { res.status(code); return this; },
    setHeader(name, value) { res.setHeader(name, value); },
    send(html) {
      const cleaned = String(html)
        .replace('<style id="panic-scanner-ux2">', '')
        .replace('</style></style>', '</style>');
      const product = `<style id="panic-scanner-product-v1">
      .psProductNav{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.psProductNav button{border:1px solid var(--line);background:#101722;color:#b9c2d1;border-radius:10px;padding:9px 11px;font-size:9px;font-weight:900}.psProductNav button.active{background:#17132a;color:#fff;border-color:#786cff77}
      .psWorkspace{margin-top:18px;padding:20px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(180deg,#101722,#0b1018)}.psWorkspaceHead{display:flex;justify-content:space-between;gap:14px;align-items:start}.psWorkspaceHead h2{margin:0;font-size:22px}.psWorkspaceHead p{color:var(--muted);font-size:10px;line-height:1.5;margin:5px 0 0}.psRisk{display:flex;gap:7px;margin:14px 0}.psRisk button{flex:1;border:1px solid var(--line);background:#0d141e;color:#aeb8ca;border-radius:11px;padding:11px;font-size:10px;font-weight:950}.psRisk button.active{color:#fff;border-color:#786cff88;background:#17132a}.psRisk button[data-risk="safe"].active{box-shadow:inset 0 0 0 1px #35d59d66}.psRisk button[data-risk="medium"].active{box-shadow:inset 0 0 0 1px #f5c85c66}.psRisk button[data-risk="risky"].active{box-shadow:inset 0 0 0 1px #ff526666}.psForm{display:grid;grid-template-columns:repeat(4,1fr);gap:9px}.psField label{display:block;color:#748096;font-size:8px;font-weight:900;text-transform:uppercase;letter-spacing:1px;margin-bottom:5px}.psField input{width:100%;background:#080d15;color:#fff;border:1px solid var(--line);border-radius:9px;padding:10px;outline:none}.psField input:focus{border-color:#786cff88}.psPlanGrid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:12px}.psMetric{padding:12px;border:1px solid var(--line);border-radius:11px;background:#0d141e}.psMetric small{display:block;color:#748096;font-size:8px}.psMetric b{display:block;font-size:15px;margin-top:4px}.psSetupExplain{margin-top:12px;padding:13px;border:1px solid #786cff44;background:#141329;border-radius:12px;color:#b8c1d1;font-size:10px;line-height:1.55}.psSetupExplain strong{color:#fff}.psSave{margin-top:12px;border:0;background:#fff;color:#07090f;border-radius:10px;padding:10px 14px;font-weight:1000}.psOpportunityGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.psOpportunity{padding:14px;border:1px solid var(--line);border-radius:13px;background:#0d141e}.psOpportunity b{font-size:11px}.psOpportunity p{color:var(--muted);font-size:9px;line-height:1.5;margin:5px 0}.psTag{display:inline-block;border:1px solid #786cff44;border-radius:99px;padding:4px 7px;color:#b9afff;font-size:8px;font-weight:900}.psTag.green{color:#58e3b2;border-color:#35d59d44}.psTag.red{color:#ff8794;border-color:#ff526644}.psLocked{padding:16px;border:1px dashed #344054;border-radius:13px;color:#8490a4;font-size:10px;line-height:1.5}.psLocked b{color:#fff}@media(max-width:900px){.psForm{grid-template-columns:1fr 1fr}.psPlanGrid{grid-template-columns:1fr 1fr}.psOpportunityGrid{grid-template-columns:1fr 1fr}}@media(max-width:620px){.psProductNav{overflow-x:auto;flex-wrap:nowrap}.psProductNav button{white-space:nowrap}.psRisk{flex-direction:column}.psForm,.psPlanGrid,.psOpportunityGrid{grid-template-columns:1fr}.psWorkspace{padding:15px}.psWorkspaceHead{display:block}}
      </style>`;
      const feature = `<script id="panic-scanner-product-v1">(function(){
        const $=id=>document.getElementById(id);
        function fmtMoney(n){return Number.isFinite(n)?n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2}):'—'}
        function openPanel(){let m=$('psProductModal');if(!m){m=document.createElement('div');m.id='psProductModal';m.className='modal';m.innerHTML='<div class="modalShell"><div class="modalHead"><div><b id="psModalTitle">Panic Scanner</b><span id="psModalSub">Research workspace</span></div><button class="close" id="psModalClose">×</button></div><div class="modalBody" id="psModalBody"></div></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('open')});$('psModalClose').onclick=()=>m.classList.remove('open')}return m}
        function show(title,sub,body){const m=openPanel();$('psModalTitle').textContent=title;$('psModalSub').textContent=sub;$('psModalBody').innerHTML=body;m.classList.add('open')}
        function setupBody(){return '<div class="psWorkspaceHead"><div><h2>Trade Setup Planner</h2><p>Build a scenario around your capital, entry, invalidation and target. This is a planning tool — not an automatic order.</p></div><span class="psTag">RISK-AWARE</span></div><div class="psRisk"><button data-risk="safe">SAFE · Conservative</button><button data-risk="medium" class="active">MEDIUM · Balanced</button><button data-risk="risky">RISKY · Aggressive</button></div><div class="psForm"><div class="psField"><label>Position money</label><input id="psMoney" type="number" min="0" value="500"></div><div class="psField"><label>Entry</label><input id="psEntry" type="number" min="0" step="0.01"></div><div class="psField"><label>Stop / invalidation</label><input id="psStop" type="number" min="0" step="0.01"></div><div class="psField"><label>Target</label><input id="psTarget" type="number" min="0" step="0.01"></div></div><div class="psPlanGrid"><div class="psMetric"><small>Units</small><b id="psUnits">—</b></div><div class="psMetric"><small>Max loss</small><b id="psLoss">—</b></div><div class="psMetric"><small>Potential gain</small><b id="psGain">—</b></div><div class="psMetric"><small>Risk / reward</small><b id="psRR">—</b></div></div><div class="psSetupExplain" id="psExplain"><strong>What we are hoping for:</strong> price holds the entry structure, confirms momentum and moves toward the target.<br><strong>What invalidates it:</strong> the stop level is breached and the original thesis is weakened.</div><button class="psSave" id="psSave">Save setup</button>'}
        function bindSetup(){const risks={safe:'Conservative scenario: prioritize confirmation and capital protection.',medium:'Balanced scenario: trade-off between confirmation, downside and upside.',risky:'Aggressive scenario: accepts more volatility for greater potential upside.'};let risk='medium';document.querySelectorAll('.psRisk button').forEach(b=>b.onclick=()=>{risk=b.dataset.risk;document.querySelectorAll('.psRisk button').forEach(x=>x.classList.remove('active'));b.classList.add('active');recalc()});function recalc(){const capital=Number($('psMoney').value),entry=Number($('psEntry').value),stop=Number($('psStop').value),target=Number($('psTarget').value);if(entry>0){const units=capital/entry,loss=units*Math.max(0,entry-stop),gain=units*Math.max(0,target-entry);$('psUnits').textContent=capital?units.toFixed(3):'—';$('psLoss').textContent=capital?'−'+fmtMoney(loss):'—';$('psGain').textContent=capital?'+'+fmtMoney(gain):'—';$('psRR').textContent=loss>0?(gain/loss).toFixed(2)+' : 1':'—'}else{$('psUnits').textContent=$('psLoss').textContent=$('psGain').textContent=$('psRR').textContent='—'}$('psExplain').innerHTML='<strong>'+risks[risk]+'</strong><br><strong>What we are hoping for:</strong> price holds the entry structure, confirms the expected signal and moves toward the target.<br><strong>What invalidates it:</strong> price reaches the stop/invalidation level or the evidence behind the thesis deteriorates.'}['psMoney','psEntry','psStop','psTarget'].forEach(id=>$(id).addEventListener('input',recalc));$('psSave').onclick=()=>{localStorage.setItem('psSetup',JSON.stringify({money:$('psMoney').value,entry:$('psEntry').value,stop:$('psStop').value,target:$('psTarget').value,risk}));toast('Setup saved to this browser.')};try{const s=JSON.parse(localStorage.getItem('psSetup')||'null');if(s){if(s.money)$('psMoney').value=s.money;if(s.entry)$('psEntry').value=s.entry;if(s.stop)$('psStop').value=s.stop;if(s.target)$('psTarget').value=s.target;risk=s.risk||'medium';document.querySelectorAll('.psRisk button').forEach(x=>x.classList.toggle('active',x.dataset.risk===risk))}}catch(e){}recalc()}
        function planner(){show('Setup Planner','Risk profiles, scenarios and position planning',setupBody());bindSetup()}
        function opportunities(){show('Opportunity Scanner','Find research candidates instead of starting with a ticker','<div class="psOpportunityGrid"><div class="psOpportunity"><span class="psTag green">RECOVERY</span><b>Oversold quality</b><p>Look for strong fundamentals combined with a stretched technical move and early stabilization.</p><button class="outline" onclick="toast(\'Scan requires live universe data.\')">Scan universe</button></div><div class="psOpportunity"><span class="psTag">MOMENTUM</span><b>Breakout watch</b><p>Look for volume expansion, improving momentum and price reclaiming important levels.</p><button class="outline" onclick="toast(\'Scan requires live universe data.\')">Scan universe</button></div><div class="psOpportunity"><span class="psTag red">CATALYST</span><b>News-driven move</b><p>Combine relevant news with abnormal price/volume behavior and investigate the reason.</p><button class="outline" onclick="toast(\'Scan requires live universe data.\')">Scan universe</button></div></div><div class="psSetupExplain"><strong>How this works:</strong> opportunities are candidates for research, not guaranteed winners. Each candidate should expose the evidence, risk and invalidation conditions before a setup is considered.</div>')}
        function thesis(){show('Thesis Builder','Turn an idea into a testable research thesis','<div class="psForm" style="grid-template-columns:1fr 1fr"><div class="psField"><label>Bull case</label><input id="psBull" placeholder="What needs to go right?"></div><div class="psField"><label>Bear case</label><input id="psBear" placeholder="What could go wrong?"></div><div class="psField"><label>Catalyst</label><input id="psCat" placeholder="What could change sentiment?"></div><div class="psField"><label>Invalidation</label><input id="psInv" placeholder="What proves the thesis wrong?"></div></div><button class="psSave" onclick="toast(\'Thesis saved for this session.\')">Save thesis</button>')}
        function bindNav(){const side=document.querySelector('.side');if(!side)return;if(!document.getElementById('psExtraNav')){const wrap=document.createElement('div');wrap.id='psExtraNav';wrap.className='psProductNav';wrap.innerHTML='<button data-ps="opps">Opportunities</button><button data-ps="setup">Setup Planner</button><button data-ps="thesis">Thesis</button>';side.appendChild(wrap);wrap.querySelector('[data-ps="opps"]').onclick=opportunities;wrap.querySelector('[data-ps="setup"]').onclick=planner;wrap.querySelector('[data-ps="thesis"]').onclick=thesis)}}
        window.psOpenSetup=planner;window.psOpenOpportunities=opportunities;window.psOpenThesis=thesis;if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bindNav);else bindNav();
      })();</script>`;
      return send(cleaned.replace('</head>',product+'</head>').replace('</body>',feature+'</body>'));
    }
  };
  return ux2(req, intercepted);
}
