import ux from './ux.js';

export default function handler(req, res) {
  const originalSend = res.send.bind(res);
  const intercepted = {
    ...res,
    status(code){res.status(code);return this;},
    setHeader(name,value){res.setHeader(name,value);},
    send(html){
      const injected = `<style id="psw-complete">#psw{position:fixed;inset:0;z-index:9999;display:none;background:#070b11eF;backdrop-filter:blur(12px);overflow:auto;padding:16px}#psw.open{display:block}#psw .box{max-width:980px;margin:4vh auto;background:#0b1119;border:1px solid #263043;border-radius:18px;padding:18px;box-shadow:0 30px 100px #000b}#psw h2{margin:0 0 4px}#psw .muted{color:#8792a5;font-size:12px}#psw .grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}#psw .card{background:#0f1722;border:1px solid #263043;border-radius:12px;padding:13px}#psw input,#psw select,#psw textarea{width:100%;box-sizing:border-box;background:#080d15;color:#fff;border:1px solid #303b4e;border-radius:8px;padding:9px;margin:4px 0 9px}#psw button{border:1px solid #3b4860;background:#151e2b;color:#fff;border-radius:8px;padding:9px 12px;font-weight:800;cursor:pointer}#psw .primary{background:#786cff;border-color:#786cff}.pswNav{display:flex;gap:6px;flex-wrap:wrap;margin:10px 0}.pswNav button{font-size:10px}@media(max-width:650px){#psw{padding:7px}#psw .box{margin:0;padding:13px}.grid{grid-template-columns:1fr!important}}</style><div id="psw"><div class="box"><div style="display:flex;justify-content:space-between;gap:10px"><div><h2 id="pswTitle">Research Workspace</h2><div class="muted" id="pswSub">Panic Scanner</div></div><button onclick="pswClose()">×</button></div><div id="pswBody"></div></div></div><div class="pswNav" id="pswNav"><button onclick="pswOpen('watch')">Watchlist</button><button onclick="pswOpen('opps')">Opportunities</button><button onclick="pswOpen('setup')">Setup Planner</button><button onclick="pswOpen('thesis')">Thesis Builder</button><button onclick="pswOpen('journal')">Journal</button><button onclick="pswOpen('settings')">Settings</button><button onclick="pswOpen('plans')">Plans & Billing</button><button onclick="pswOpen('account')">Account</button><button id="pswAdmin" onclick="pswOpen('admin')" style="display:none">Admin / VIP</button></div><script>(function(){
const K='pswWorkspaceV3';const D={watch:[],setups:[],theses:[],journal:[],settings:{sound:true,haptic:true,reduce_motion:false,compact:false,volume:70,research_range:'60',chart_detail:'standard',notifications:true},profile:null};
const $=id=>document.getElementById(id);const read=()=>{try{return Object.assign({},D,JSON.parse(localStorage.getItem(K)||'{}'),{settings:Object.assign({},D.settings,(JSON.parse(localStorage.getItem(K)||'{}').settings||{}))})}catch{return JSON.parse(JSON.stringify(D))}};const save=x=>localStorage.setItem(K,JSON.stringify(x));const tok=()=>localStorage.getItem('pswAccessToken')||'';
async function api(path,opt={}){const h=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(tok())h.Authorization='Bearer '+tok();const r=await fetch(path,Object.assign({},opt,{headers:h}));const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
async function sync(){if(!tok())return;try{const d=await api('/api/account');let x=read();x.profile=d.profile||null;x.settings=Object.assign(x.settings,d.settings||{});x.watch=d.watchlist||[];x.setups=d.setups||[];x.theses=d.theses||[];x.journal=d.journal||[];save(x);$('pswAdmin').style.display=x.profile?.is_admin?'':'none';applySettings(x.settings)}catch(e){console.warn(e)}}
async function persist(){if(!tok())return;const x=read();try{await api('/api/account',{method:'PUT',body:JSON.stringify({settings:x.settings,watchlist:x.watch,setups:x.setups,theses:x.theses,journal:x.journal})})}catch(e){console.warn(e)}}
function applySettings(s){document.documentElement.style.setProperty('--psw-motion',s.reduce_motion?'0s':'.15s');document.body.classList.toggle('psw-compact',!!s.compact)}
window.pswClose=()=>{$('psw').classList.remove('open')};window.pswShow=(t,sub,b)=>{$('pswTitle').textContent=t;$('pswSub').textContent=sub||'';$('pswBody').innerHTML=b;$('psw').classList.add('open')};
async function quote(s){return api('/api/stock?symbol='+encodeURIComponent(s))}
window.pswOpen=function(k){const x=read();if(k==='watch'){let h='<div class="grid"><div><label>Ticker</label><input id="wa" placeholder="MU"></div><div style="padding-top:24px"><button class="primary" onclick="pswAdd()">Add stock</button></div></div><div id="wl">';h+=x.watch.length?x.watch.map(s=>`<div class="card"><b>${esc(s)}</b><div id="q_${esc(s)}">Loading live quote…</div><button onclick="pswAnalyze('${esc(s)}')">Analyze</button> <button onclick="pswRemove('${esc(s)}')">Remove</button></div>`).join(''):'<div class="card">Your watchlist is empty.</div>';pswShow('Watchlist','Live securities and research',h+'</div>');x.watch.forEach(s=>quote(s).then(d=>{const e=$('q_'+s);if(e)e.textContent=`Price ${d.price??'—'} · Move ${d.changePercent??'—'} · Panic ${d.panic?.score??'—'}`}).catch(e=>{const z=$('q_'+s);if(z)z.textContent=e.message}));}
else if(k==='opps'){pswShow('Opportunity Scanner','Find candidates from real market data','<div class="grid"><div><label>Ticker</label><input id="opp" placeholder="NVDA"></div><div><label>Style</label><select id="oppStyle"><option>Oversold recovery</option><option>Momentum breakout</option><option>Unusual movement</option><option>News driven</option><option>Technical + fundamental</option></select></div><div style="padding-top:24px"><button class="primary" onclick="pswOpp()">Scan</button></div></div><div id="oppOut" class="card">Enter a ticker to evaluate it. Results are research signals, not guarantees.</div>')}
else if(k==='setup'){pswShow('Setup Planner','Risk/reward and position sizing','<div class="grid"><div><label>Ticker</label><input id="st" placeholder="MU"></div><div><label>Capital / position (NOK)</label><input id="cap" type="number" value="10000"></div><div><label>Entry</label><input id="en" type="number"></div><div><label>Stop</label><input id="sl" type="number"></div><div><label>Target</label><input id="tg" type="number"></div><div><label>Risk profile</label><select id="rp"><option>Conservative</option><option selected>Balanced</option><option>Aggressive</option></select></div></div><label>Thesis / notes</label><textarea id="sn" rows="3"></textarea><button class="primary" onclick="pswCalcSetup()">Calculate & Save</button><div id="setupOut" class="card" style="margin-top:12px">Set entry, stop and target to calculate shares, max loss, potential gain and R/R.</div>')}
else if(k==='thesis'){pswShow('Thesis Builder','Structured bull/bear research','<div class="grid"><div><label>Ticker</label><input id="tt"></div><div><label>Confirmation</label><input id="tc"></div><div><label>Invalidation</label><input id="ti"></div></div><label>Bull case</label><textarea id="tb" rows="3"></textarea><label>Bear case</label><textarea id="tr" rows="3"></textarea><label>Catalysts</label><textarea id="tcat" rows="2"></textarea><label>Risks</label><textarea id="trisk" rows="2"></textarea><button class="primary" onclick="pswSaveThesis()">Save Thesis</button>')}
else if(k==='journal'){const rows=x.journal||[];pswShow('Journal','Saved research and outcomes',rows.length?rows.map(j=>`<div class="card"><b>${esc(j.symbol||'Research')} · ${esc(j.type||'Entry')}</b><div class="muted">${esc(j.date||'')}</div><p>${esc(j.body||j.score||'')}</p></div>`).join(''):'<div class="card">No journal entries yet.</div>')}
else if(k==='settings'){const s=x.settings;pswShow('Settings','Preferences persist to your account when signed in',`<div class="grid"><div class="card"><b>Sound</b><p>UI/research sound</p><button onclick="pswSet('sound',${!s.sound})">${s.sound?'ON':'OFF'}</button></div><div class="card"><b>Haptics</b><p>Supported device feedback</p><button onclick="pswSet('haptic',${!s.haptic})">${s.haptic?'ON':'OFF'}</button></div><div class="card"><b>Reduce motion</b><p>Less animation</p><button onclick="pswSet('reduce_motion',${!s.reduce_motion})">${s.reduce_motion?'ON':'OFF'}</button></div><div class="card"><label>Volume ${s.volume}%</label><input type="range" min="0" max="100" value="${s.volume}" onchange="pswSet('volume',+this.value)"></div><div class="card"><label>Chart range</label><select onchange="pswSet('research_range',this.value)"><option ${s.research_range==='30'?'selected':''}>30</option><option ${s.research_range==='60'?'selected':''}>60</option><option ${s.research_range==='120'?'selected':''}>120</option></select></div><div class="card"><b>Compact mode</b><p>Denser research layout</p><button onclick="pswSet('compact',${!s.compact})">${s.compact?'ON':'OFF'}</button></div></div>`)}
else if(k==='plans'){pswShow('Plans & Billing','Real Stripe subscriptions','<div class="grid"><div class="card"><h3>Standard</h3><p>Core scanner, charts, basic research.</p><button>Current / Free</button></div><div class="card"><h3>Pro · 149 NOK/mo</h3><p>Deep investigations, catalysts, thesis tools, expanded setups.</p><button class="primary" onclick="pswCheckout(\'pro\',\'monthly\')">Choose Pro</button><button onclick="pswCheckout(\'pro\',\'yearly\')">Yearly · 1,499 NOK</button></div><div class="card"><h3>Elite · 299 NOK/mo</h3><p>Everything in Pro plus advanced reaction mapping and unlimited research setups.</p><button class="primary" onclick="pswCheckout(\'elite\',\'monthly\')">Choose Elite</button><button onclick="pswCheckout(\'elite\',\'yearly\')">Yearly · 2,990 NOK</button></div></div><div class="card"><button onclick="pswPortal()">Manage existing subscription</button><p class="muted">Checkout is handled by Stripe. Your plan activates from the verified subscription webhook.</p></div>')}
else if(k==='account'){pswShow('Account','Authentication and entitlement',`<div class="card"><b>${esc(x.profile?.email||'Not signed in')}</b><p>Plan: ${esc(x.profile?.plan||'standard')} · Admin: ${x.profile?.is_admin?'Yes':'No'} · VIP: ${x.profile?.is_vip?'Yes':'No'}</p></div><div class="grid"><div><label>Email</label><input id="ae" type="email"></div><div><label>Password</label><input id="ap" type="password"></div><div style="padding-top:24px"><button class="primary" onclick="pswAuth(false)">Sign in</button> <button onclick="pswAuth(true)">Create account</button></div></div><button onclick="pswLogout()">Sign out</button>`)}
else if(k==='admin'){api('/api/admin').then(d=>{pswShow('Admin / VIP','Server-authorized administration',`<div class="card"><b>Users</b><p>${d.users.length} accounts</p></div><div class="card"><b>Promo codes</b><p>${d.promos.length} codes</p><label>New code</label><input id="pc" placeholder="LAUNCH25"><label>Plan</label><select id="pp"><option>pro</option><option>elite</option><option>standard</option></select><label>Discount %</label><input id="pd" type="number" value="25"><button class="primary" onclick="pswPromo()">Create promo</button></div>`)}).catch(e=>pswShow('Admin / VIP','Access denied',`<div class="card">${esc(e.message)}</div>`))}}
window.pswAdd=()=>{let x=read(),s=($('wa').value||'').trim().toUpperCase();if(s&&!x.watch.includes(s)){x.watch.push(s);save(x);persist()}pswOpen('watch')};window.pswRemove=s=>{let x=read();x.watch=x.watch.filter(v=>v!==s);save(x);persist();pswOpen('watch')};
window.pswAnalyze=async s=>{pswShow('Analysis',s,'<div id="ao" class="card">Loading real market data…</div>');try{const d=await quote(s);$('ao').innerHTML=`<div class="grid"><div class="card"><b>Price</b><h3>${esc(d.price)}</h3></div><div class="card"><b>Move</b><h3>${esc(d.changePercent)}</h3></div><div class="card"><b>Panic score</b><h3>${esc(d.panic?.score??'—')}</h3></div><div class="card"><b>RSI</b><h3>${esc(d.technicals?.rsi14??'—')}</h3></div><div class="card"><b>SMA20</b><h3>${esc(d.technicals?.sma20??'—')}</h3></div><div class="card"><b>Drawdown 20d</b><h3>${esc(d.technicals?.drawdown20??'—')}</h3></div></div><button class="primary" onclick="pswSaveJournal('${esc(s)}','${esc(d.panic?.score??'')}')">Save investigation</button><h3>Live news</h3><div id="news">Loading…</div>`;api('/api/news?symbol='+encodeURIComponent(s)).then(n=>{$('news').innerHTML=(n.articles||[]).map(a=>`<div class="card"><b>${esc(a.title)}</b><div class="muted">${esc(a.source)} · ${esc(a.sentiment)} · ${esc(a.time)}</div></div>`).join('')||'No relevant live articles.'}).catch(e=>{$('news').textContent=e.message})}catch(e){$('ao').textContent=e.message}};
window.pswSaveJournal=(s,score)=>{let x=read();x.journal.unshift({type:'investigation',symbol:s,score,date:new Date().toISOString()});save(x);persist();alert('Saved to Journal')};
window.pswOpp=async()=>{const s=($('opp').value||'').trim().toUpperCase();if(!s)return;const o=$('oppOut');o.textContent='Scanning…';try{const d=await quote(s);o.innerHTML=`<b>${esc(s)}</b><p>Price: ${esc(d.price)} · Move: ${esc(d.changePercent)} · RSI: ${esc(d.technicals?.rsi14??'—')} · Panic: ${esc(d.panic?.score??'—')}</p><p>Signal context is descriptive only. Confirm fundamentals, catalyst and invalidation before acting.</p>`}catch(e){o.textContent=e.message}};
window.pswCalcSetup=()=>{const s=($('st').value||'').trim().toUpperCase(),capital=+$('cap').value,entry=+$('en').value,stop=+$('sl').value,target=+$('tg').value,profile=$('rp').value;if(!(entry>0&&stop>0&&target>0&&capital>0))return alert('Enter valid capital, entry, stop and target.');const riskPer=Math.abs(entry-stop),rewardPer=Math.abs(target-entry),shares=Math.floor(capital/entry),maxLoss=shares*riskPer,gain=shares*rewardPer,rr=rewardPer/riskPer;let x=read();const setup={symbol:s,capital,entry,stop,target,profile,shares,maxLoss,potentialGain:gain,rr,date:new Date().toISOString(),notes:$('sn').value};x.setups.unshift(setup);save(x);persist();$('setupOut').innerHTML=`<b>${esc(profile)} setup</b><p>Shares: ${shares} · Max loss: ${maxLoss.toFixed(2)} · Potential gain: ${gain.toFixed(2)} · R/R: ${rr.toFixed(2)} · Downside: ${(riskPer/entry*100).toFixed(2)}% · Upside: ${(rewardPer/entry*100).toFixed(2)}%</p><p>Stop is based on your chosen invalidation; profile does not move it merely to improve the ratio.</p>`};
window.pswSaveThesis=()=>{let x=read();x.theses.unshift({symbol:$('tt').value.toUpperCase(),bull:$('tb').value,bear:$('tr').value,catalysts:$('tcat').value,risks:$('trisk').value,confirmation:$('tc').value,invalidation:$('ti').value,date:new Date().toISOString()});save(x);persist();alert('Thesis saved')};
window.pswSet=(k,v)=>{let x=read();x.settings[k]=v;save(x);applySettings(x.settings);persist();pswOpen('settings')};
window.pswCheckout=async(plan,interval)=>{try{const d=await api('/api/billing',{method:'POST',body:JSON.stringify({action:'checkout',plan,interval})});if(!d.url)throw Error('Checkout session was not created.');location.href=d.url}catch(e){alert(e.message)}};window.pswPortal=async()=>{try{const d=await api('/api/billing',{method:'POST',body:JSON.stringify({action:'portal'})});location.href=d.url}catch(e){alert(e.message)}};
window.pswPromo=async()=>{try{const d=await api('/api/admin',{method:'POST',body:JSON.stringify({code:$('pc').value,plan:$('pp').value,discount_percent:+$('pd').value})});alert('Promo '+d.promo.code+' created')}catch(e){alert(e.message)}};
window.pswAuth=async signup=>{try{const d=await api('/api/auth',{method:'POST',body:JSON.stringify({action:signup?'signup':'login',email:$('ae').value.trim(),password:$('ap').value})});if(!d.access_token)return alert('Account created. Check your email if confirmation is required.');localStorage.setItem('pswAccessToken',d.access_token);if(d.refresh_token)localStorage.setItem('pswRefreshToken',d.refresh_token);await sync();pswOpen('account')}catch(e){alert(e.message)}};window.pswLogout=()=>{localStorage.removeItem('pswAccessToken');localStorage.removeItem('pswRefreshToken');localStorage.removeItem('psLoggedIn');location.reload()};
function esc(v){return String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}applySettings(read().settings);sync();
})();</script>`;
      let out=String(html);const marker='</body>';if(out.toLowerCase().includes(marker))out=out.replace(/<\/body>/i,injected+'</body>');else out+=injected;originalSend(out);
    }
  };
  return ux(req,intercepted);
}
