const fs=require('fs');const path=require('path');
module.exports=async function handler(req,res){try{const html=fs.readFileSync(path.join(process.cwd(),'index.html'),'utf8');const patch=`
<style>
#psTools{position:fixed;top:14px;right:14px;z-index:10000;display:flex;gap:8px;font:14px system-ui}#psTools button{border:1px solid #39455b;background:#111925;color:#fff;border-radius:11px;padding:10px 13px;font-weight:800;cursor:pointer;box-shadow:0 8px 30px #0008}#psTools .ai{background:linear-gradient(135deg,#786cff,#4f8cff);border-color:#8b7cff}#psPanel{display:none;position:fixed;z-index:10001;right:14px;top:58px;width:min(520px,calc(100vw - 28px));max-height:82vh;overflow:auto;background:linear-gradient(180deg,#0d1420,#090e16);border:1px solid #293448;border-radius:20px;padding:18px;box-shadow:0 25px 90px #000d;color:#fff;font:14px system-ui}#psPanel.open{display:block}.psClose{float:right;border:1px solid #39455b;background:#111925;color:#fff;border-radius:9px;padding:7px 10px;cursor:pointer}.psTitle{font-size:21px;font-weight:950;margin:0 0 4px}.psSub,.psFine{color:#9aa6b9;font-size:12px;line-height:1.5}.psBox{padding:12px;border:1px solid #293448;border-radius:13px;background:#0b1119;margin-top:10px}.psInput{width:100%;box-sizing:border-box;background:#080d15;color:#fff;border:1px solid #303b4e;border-radius:10px;padding:11px;margin:5px 0}.psRow{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.psBtn{border:1px solid #39455b;background:#111925;color:#fff;border-radius:10px;padding:10px 13px;font-weight:850;cursor:pointer}.psPrimary{background:#786cff;border-color:#786cff}.psGold{background:linear-gradient(135deg,#f5c85c,#c99432);color:#17110a;border-color:#f5c85c}.psChat{display:flex;flex-direction:column;gap:9px;max-height:40vh;overflow:auto;padding:5px 0}.psBubble{max-width:88%;padding:11px 13px;border-radius:14px;line-height:1.5;font-size:12px;white-space:pre-wrap}.psUser{align-self:flex-end;background:#201b3d}.psBot{align-self:flex-start;background:#111a26}.psGrid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.psMetric{padding:10px;border:1px solid #202a39;border-radius:10px;background:#0a0f17}.psMetric small{display:block;color:#7f8ba0;font-size:9px}.psMetric b{display:block;font-size:16px;margin-top:3px}@media(max-width:600px){#psTools{top:10px;right:10px}#psTools button{padding:9px 11px}#psPanel{right:10px;top:54px;width:calc(100vw - 20px);max-height:84vh}.psGrid{grid-template-columns:1fr 1fr}}
</style>
<div id="psTools"><button class="ai" onclick="psOpenAi()">✦ Panic AI</button><button onclick="psOpenSettings()">⚙ Settings</button></div>
<div id="psPanel"><button class="psClose" onclick="psClosePanel()">Close</button><div id="psPanelBody"></div></div>
<script>
(function(){
var tokenKey='pswAccessToken',refreshKey='pswRefreshToken',tier='standard',profile=null;
function token(){return localStorage.getItem(tokenKey)||''}function esc(v){return String(v??'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}function msg(s){var e=document.getElementById('psMsg');if(e)e.textContent=s||''}
async function api(path,opts){var r=await fetch(path,Object.assign({headers:{'Content-Type':'application/json',Authorization:'Bearer '+token()}},opts||{}));var d=await r.json().catch(function(){return{}});if(!r.ok)throw Error(d.error||'Request failed');return d}
async function loadAccount(){if(!token())return null;try{var d=await api('/api/account');profile=d.profile||{};tier=(profile.is_admin||profile.is_vip)?'elite':String(profile.plan||'Standard').toLowerCase();if(tier!=='elite'&&tier!=='pro')tier='standard';document.getElementById('auth')?.classList.add('hidden');var map=document.querySelector('.eliteMap');if(map)map.style.display=tier==='elite'?'':'none';return d}catch(e){localStorage.removeItem(tokenKey);localStorage.removeItem(refreshKey);document.getElementById('auth')?.classList.remove('hidden');return null}}
async function auth(action){var email=(document.getElementById('email')||{}).value?.trim()||'',password=(document.getElementById('password')||{}).value||'';if(!email||!password)return toast('Enter your email and password.');var r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:action,email:email,password:password})});var d=await r.json();if(!r.ok)throw Error(d.error||'Authentication failed.');if(!d.access_token){toast('Account created. Check your email if confirmation is required.');return}localStorage.setItem(tokenKey,d.access_token);if(d.refresh_token)localStorage.setItem(refreshKey,d.refresh_token);document.getElementById('auth')?.classList.add('hidden');await loadAccount();toast('Signed in.');}
window.enterApp=function(){auth('login').catch(e=>toast(e.message))};window.createAccount=function(){auth('signup').catch(e=>toast(e.message))};window.demoLogin=function(){toast('Demo access is disabled. Create a free account to continue.')};window.logout=function(){localStorage.removeItem(tokenKey);localStorage.removeItem(refreshKey);location.reload()};window.psLogout=window.logout;
window.startCheckout=async function(plan,interval){if(!token())return toast('Sign in first.');try{toast('Opening secure Stripe checkout…');var d=await api('/api/billing',{method:'POST',body:JSON.stringify({action:'checkout',plan:plan,interval:interval})});if(d.url)location.href=d.url;else throw Error('Checkout URL missing.')}catch(e){toast(e.message)}};
window.psOpenBilling=function(){openModal('accountModal');loadAccount()};
var oldOpen=window.openModal,oldClose=window.closeModal;window.openModal=function(id){if(oldOpen)oldOpen(id);if(id==='settingsModal')loadSettings();if(id==='accountModal')loadAccount()};window.closeModal=function(id){if(oldClose)oldClose(id)};
async function loadSettings(){try{var d=await api('/api/account'),s=d.settings||{};var groups=document.querySelectorAll('#settingsModal .settingGroup');var toggles=document.querySelectorAll('#settingsModal .toggle');if(toggles[0])toggles[0].classList.toggle('on',!!s.compact_mode);if(toggles[1])toggles[1].classList.toggle('on',!!s.reduce_motion);var select=document.querySelector('#settingsModal select');if(select&&s.research_range)select.value=String(s.research_range).replace(/[^0-9A-Z]/gi,'').toUpperCase()==='ALL'?'ALL':String(s.research_range)+'D';}catch(e){}}
var saveTimer;function saveSettings(){clearTimeout(saveTimer);saveTimer=setTimeout(async function(){try{var toggles=document.querySelectorAll('#settingsModal .toggle'),select=document.querySelector('#settingsModal select'),range=document.querySelector('#settingsModal .range');await api('/api/account',{method:'PUT',body:JSON.stringify({settings:{reduce_motion:!!toggles[1]?.classList.contains('on'),compact_mode:!!toggles[0]?.classList.contains('on'),research_range:(select?.value||'60D').replace('D',''),chart_detail:Number(range?.value||2)}})});toast('Settings saved.')}catch(e){toast(e.message)}},350)}
document.addEventListener('click',function(e){var b=e.target.closest('#settingsModal .toggle');if(b)saveSettings();var s=e.target.closest('#settingsModal select');if(s)saveSettings();var r=e.target.closest('#settingsModal .range');if(r)saveSettings()});
function requireAuth(){if(!token()){document.getElementById('auth')?.classList.remove('hidden');toast('Sign in to investigate.');return false}return true}
var oldAnalyze=window.analyze;window.analyze=async function(symbol,name){if(typeof oldAnalyze!=='function')return;return oldAnalyze(symbol,name)};
var oldInvestigate=window.investigate;window.investigate=async function(){if(!requireAuth())return;var s=current?.symbol;if(!s)return toast('Analyze a stock first.');var depth=tier==='elite'?'elite':tier==='pro'?'pro':'standard';try{toast('Running '+depth+' investigation…');var r=await api('/api/investigate?symbol='+encodeURIComponent(s)+'&depth='+depth,{method:'GET'});current.investigation=r;var q=r.investigation?.quality??50;document.getElementById('qualityBar').style.width=q+'%';document.getElementById('qualityScore').textContent=q;document.getElementById('stressScore').textContent=current.panic.score;document.getElementById('stressBar').style.width=current.panic.score+'%';var recovery=Math.max(0,Math.min(100,Math.round(100-current.panic.score*.55+q*.2)));document.getElementById('recoveryBar').style.width=recovery+'%';document.getElementById('recoveryScore').textContent=recovery;document.getElementById('finalScore').textContent=Math.max(0,Math.min(100,Math.round((q+(100-current.panic.score))/2)));document.getElementById('finalVerdict').textContent=r.investigation?.verdict||'Research view assembled';document.getElementById('finalText').textContent=(r.investigation?.steps||[]).map(function(x){return x.detail||x.label}).join(' ')||'Evidence assembled.';if(typeof drawNews==='function')drawNews(r.news?.articles||[]);if(r.investigation?.steps)document.getElementById('steps').innerHTML=r.investigation.steps.map(function(s,i){return '<div class="step '+(s.status==='complete'?'done':'')+'"><b>0'+(i+1)+' · '+esc(s.label)+'</b><small>'+esc(s.detail||s.status)+'</small></div>'}).join('');document.getElementById('whatChanged').innerHTML='<div class="bullet">'+esc(s)+' investigation completed at '+esc(new Date(r.generatedAt).toLocaleString())+'.</div><div class="bullet">News context: '+Number(r.news?.positive||0)+' positive/bullish and '+Number(r.news?.negative||0)+' negative/bearish recent articles.</div>';if(typeof drawElite==='function')drawElite();toast('Investigation complete.')}catch(e){toast(e.message)}};
function openPanel(body){document.getElementById('psPanelBody').innerHTML=body;document.getElementById('psPanel').classList.add('open')}window.psClosePanel=function(){document.getElementById('psPanel').classList.remove('open')};window.psOpenSettings=function(){openPanel('<div class="psTitle">Settings</div><p class="psSub">Account settings are saved to your Panic Scanner profile.</p><div class="psBox"><b>Research access</b><p>Free: 1 deep investigation per day · Pro: expanded research · Elite: advanced research, Personal Investment AI and Investment Planner.</p><button class="psBtn" onclick="openModal(\\'settingsModal\\');psClosePanel()">Open full settings</button></div>')};
function chat(mode,message,chatId){if(!message.trim())return;var c=document.getElementById(chatId);c.insertAdjacentHTML('beforeend','<div class="psBubble psUser">'+esc(message)+'</div>');c.scrollTop=c.scrollHeight;return api('/api/investigate?mode='+mode,{method:'POST',body:JSON.stringify({message:message})}).then(function(d){c.insertAdjacentHTML('beforeend','<div class="psBubble psBot">'+esc(d.answer)+'</div>');c.scrollTop=c.scrollHeight}).catch(function(e){c.insertAdjacentHTML('beforeend','<div class="psBubble psBot">'+esc(e.message)+'</div>')})}
window.psOpenAi=function(){if(!requireAuth())return;openPanel('<div class="psTitle">✦ Personal Investment AI</div><p class="psSub">Challenge your thesis, review your research and pressure-test a disciplined investment plan.</p><div id="psAiChat" class="psChat"><div class="psBubble psBot">I can challenge your thesis, review saved research, or pressure-test a risk plan.</div></div><textarea id="psAiInput" class="psInput" rows="3" placeholder="Ask your Panic AI…"></textarea><div class="psRow"><button class="psBtn" onclick="psQuick(\'Challenge my latest investment thesis and tell me what could make it wrong.\')">Challenge thesis</button><button class="psBtn" onclick="psQuick(\'Review my recent Panic Scanner research and tell me what deserves attention.\')">Review research</button><button class="psBtn psGold" onclick="psOpenPlanner()">Investment Planner</button><button class="psBtn psPrimary" onclick="psSendAi()">Ask AI</button></div>')};window.psSendAi=function(){var e=document.getElementById('psAiInput');if(e){var m=e.value.trim();e.value='';chat('ai',m,'psAiChat')}};window.psQuick=function(m){chat('ai',m,'psAiChat')};
window.psOpenSupport=function(){if(!requireAuth())return;openPanel('<div class="psTitle">Panic Scanner Support</div><p class="psSub">Product support for research, plans, settings and billing.</p><div id="psSupportChat" class="psChat"><div class="psBubble psBot">Hi — tell me what you need help with.</div></div><textarea id="psSupportInput" class="psInput" rows="3" placeholder="What do you need help with?"></textarea><div class="psRow"><button class="psBtn psPrimary" onclick="psSendSupport()">Get help</button></div>')};window.psSendSupport=function(){var e=document.getElementById('psSupportInput');if(e){var m=e.value.trim();e.value='';chat('support',m,'psSupportChat')}};
window.psOpenPlanner=function(){if(!requireAuth()||tier!=='elite')return tier!=='elite'&&toast('The Investment Planner is an Elite feature.');openPanel('<div class="psTitle">♜ Elite Investment Planner</div><p class="psSub">Turn your capital, maximum acceptable loss and invalidation distance into a disciplined position plan.</p><div class="psBox"><input id="psCapital" class="psInput" type="number" min="0" step="100" value="100000" placeholder="Capital available (NOK)"><input id="psLoss" class="psInput" type="number" min="0" step="50" value="2000" placeholder="Maximum loss willing to take (NOK)"><input id="psStop" class="psInput" type="number" min="0.1" max="90" step="0.1" value="8" placeholder="Invalidation / stop distance %"><div class="psGrid"><div class="psMetric"><small>Risk %</small><b id="ppRisk">2.00%</b></div><div class="psMetric"><small>Max position</small><b id="ppPosition">25,000 NOK</b></div><div class="psMetric"><small>Max loss</small><b id="ppLoss">2,000 NOK</b></div><div class="psMetric"><small>Remaining capital</small><b id="ppRemain">75,000 NOK</b></div></div><div class="psRow"><button class="psBtn psPrimary" onclick="psCalcPlan()">Calculate</button><button class="psBtn" onclick="psPlanAi()">Ask AI to challenge it</button></div><p id="ppExplain" class="psFine"></p></div>');psCalcPlan()};window.psCalcPlan=function(){var c=Math.max(0,Number(document.getElementById('psCapital')?.value||0)),l=Math.max(0,Number(document.getElementById('psLoss')?.value||0)),s=Math.max(.1,Math.min(90,Number(document.getElementById('psStop')?.value||8))),pct=c?l/c*100:0,pos=s?Math.min(c,l/(s/100)):0;document.getElementById('ppRisk').textContent=pct.toFixed(2)+'%';document.getElementById('ppPosition').textContent=Math.round(pos).toLocaleString('en-NO')+' NOK';document.getElementById('ppLoss').textContent=Math.round(l).toLocaleString('en-NO')+' NOK';document.getElementById('ppRemain').textContent=Math.round(Math.max(0,c-pos)).toLocaleString('en-NO')+' NOK';document.getElementById('ppExplain').textContent='At a '+s.toFixed(1)+'% invalidation distance, this position size keeps the planned loss near the amount you entered. Validate the thesis and execution assumptions before risking capital.'};window.psPlanAi=function(){psCalcPlan();var c=Number(document.getElementById('psCapital').value||0),l=Number(document.getElementById('psLoss').value||0),s=Number(document.getElementById('psStop').value||8);window.psOpenAi();setTimeout(function(){var e=document.getElementById('psAiInput');if(e){e.value='Challenge this investment plan: capital '+Math.round(c).toLocaleString('en-NO')+' NOK, maximum loss '+Math.round(l).toLocaleString('en-NO')+' NOK, invalidation distance '+s.toFixed(1)+'%. Tell me what assumptions and evidence I should verify.';psSendAi()}},50)};
loadAccount();
})();
</script>`;return res.status(200).send(html.replace('</body>',patch+'</body>'))}catch(e){console.error('workspace error',e);return res.status(500).json({error:'Workspace failed to load.'})}};